// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivbfmlevbzdjjspptixc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2YmZtbGV2YnpkampzcHB0aXhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMzgzMzEsImV4cCI6MjA2NzgxNDMzMX0.eOq2xj1OAJHGFKG0jKZNR_vcH2ilpAG4A4S9admGq08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});